CREATE TABLE IF NOT EXISTS `Run` (
	`id`	INTEGER PRIMARY KEY AUTOINCREMENT,
	`date`	INTEGER,
	`start_time`	TEXT UNIQUE,
	`duration`	INTEGER,
	`seconds_paused`	INTEGER,
	`calories_burned`	INTEGER,
	`calories_burned_carbs`	INTEGER,
	`calories_burned_fats`	INTEGER,
	`cardio_benefit` TEXT,
	`HR_lowest`	INTEGER,
	`HR_peak`	INTEGER,
	`HR_average`	INTEGER,
	`UV`	INTEGER,
	`UV_exposure_seconds`	INTEGER,
	`distance`	INTEGER,
	`HR_invalid_min`	INTEGER,
	`HR_very_light_min`	INTEGER,
	`HR_light_min`	INTEGER,
	`HR_moderate_min`	INTEGER,
	`HR_hard_min`	INTEGER,
	`HR_very_hard_min`	INTEGER,
	`HR_finish`	INTEGER,
	`HR_recovery_1_min`	INTEGER,
	`HR_recovery_2_min`	INTEGER,
	`recovery_time_seconds`	INTEGER,
	`elevation_highest_meters`	INTEGER,
	`elevation_lowest_meters`	INTEGER,
	`elevation_gain_meters`	INTEGER,
	`elevation_loss_meters`	INTEGER,
	`distance_rule`	TEXT,
	`time_rule` TEXT,
	`pace_data`	TEXT,
	`HR_data`	TEXT,
	`elevation_data`	TEXT,
    `split_distance`	TEXT,
    `split_pace`	TEXT,
    `split_HR`	TEXT,
	`data_source`	TEXT,
	`comment`	TEXT
);

CREATE TABLE IF NOT EXISTS `Exercise` (
	`id`	INTEGER PRIMARY KEY AUTOINCREMENT,
	`date`	INTEGER,
	`start_time`	INTEGER UNIQUE,
	`duration`	INTEGER,
	`seconds_paused`	INTEGER,
	`calories_burned`	INTEGER,
	`calories_burned_carbs`	INTEGER,
	`calories_burned_fats`	INTEGER,
	`cardio_benefit` TEXT,
	`HR_lowest`	INTEGER,
	`HR_peak`	INTEGER,
	`HR_average`	INTEGER,
	`UV`	INTEGER,
	`UV_exposure_seconds`	INTEGER,
	`HR_invalid_min`	INTEGER,
	`HR_very_light_min`	INTEGER,
	`HR_light_min`	INTEGER,
	`HR_moderate_min`	INTEGER,
	`HR_hard_min`	INTEGER,
	`HR_very_hard_min`	INTEGER,
	`HR_finish`	INTEGER,
	`HR_recovery_1_min`	INTEGER,
	`HR_recovery_2_min`	INTEGER,
	`recovery_time_seconds`	INTEGER,
	`HR_data`	TEXT,
	`data_source`	TEXT,
	`comment`	TEXT
);

CREATE TABLE IF NOT EXISTS `Sleep` (
	`id`	INTEGER PRIMARY KEY AUTOINCREMENT,
	`date`	INTEGER,
	`start_time`	TEXT UNIQUE,
	`duration`	INTEGER,
	`calories_burned`	INTEGER,
	`HR_lowest`	INTEGER,
	`HR_peak`	INTEGER,
	`HR_average`	INTEGER,
	`wake_up_time`	INTEGER,
	`seconds_awake`	INTEGER,
	`seconds_asleep_total`	INTEGER,
	`seconds_asleep_restful`	INTEGER,
	`seconds_asleep_light`	INTEGER,
	`wake_ups`	INTEGER,
	`seconds_to_fall_asleep`	INTEGER,
	`sleep_efficiency`	INTEGER,
	`sleep_restoration`	INTEGER,
	`sleep_HR_resting`	INTEGER,
	`sleep_auto_detect`	TEXT,
	`bed_time_goal_met`	TEXT,
	`wake_up_time_goal_met`	TEXT,
	`sequences_start`	TEXT,
	`sequences_end`	TEXT,
	`sequences_type`	TEXT,
	`sleep_type`	TEXT,
	`HR_duration`	TEXT,
	`HR_data`	TEXT,
	`data_source`	TEXT
);

CREATE TABLE IF NOT EXISTS `Daily` (
	`id`	INTEGER PRIMARY KEY AUTOINCREMENT,
	`date`	INTEGER UNIQUE,
	`steps`	INTEGER,
	`calories`	INTEGER,
	`HR_lowest`	INTEGER,
	`HR_highest`	INTEGER,
	`HR_average`	INTEGER,
	`active_hours`	INTEGER,
	`floors_climbed`	INTEGER,
	`uv_exposure_minutes`	INTEGER,
	`total_seconds_all_activities`	INTEGER,
	`total_calories_all_activities`	INTEGER,
	`sleep_events`	INTEGER,
	`sleep_total_calories`	INTEGER,
	`total_seconds_slept`	INTEGER,
	`run_events`	INTEGER,
	`run_total_seconds`	INTEGER,
	`total_kilometers_ran`	NUMERIC,
	`run_total_calories`	INTEGER,
	`bike_events`	INTEGER,
	`bike_total_seconds`	INTEGER,
	`total_kilometers_biked`	NUMERIC,
	`bike_total_calories`	INTEGER,
	`exercise_events`	INTEGER,
	`exercise_total_seconds`	INTEGER,
	`exercise_total_calories`	INTEGER,
	`guided_workout_events`	INTEGER,
	`guided_workout_total_seconds`	INTEGER,
	`guided_workout_total_calories`	INTEGER,
	`golf_events`	INTEGER,
	`golf_total_seconds`	INTEGER,
	`total_kilometers_golfed`	INTEGER,
	`golf_total_calories`	INTEGER,
	`steps_data`	TEXT,
	`calories_data`	TEXT,
	`HR_data`	TEXT,
	`distance_data`	TEXT,
	`steps_active_data`	TEXT,
	`calories_active_data`	TEXT,
	`floors_data`	TEXT,
	`UV_data`	TEXT,
	`calories_goal`	INTEGER,
	`steps_goal`	INTEGER,
	`total_distance`	INTEGER,
	`total_distance_on_foot`	INTEGER,
	`data_source`	TEXT,
	`comment`	TEXT
);

CREATE VIEW IF NOT EXISTS `AllActivity` AS
	SELECT 
	'r'||`id` AS `id`,`date`,`duration`,`seconds_paused`,`calories_burned`,`calories_burned_carbs`,`calories_burned_fats`,
	`HR_lowest`,`HR_peak`,`HR_average`,`time_rule`,`HR_data`,`UV`,`UV_exposure_seconds`,`cardio_benefit`, "Run" AS `event_type`
	FROM `Run`

	UNION ALL

	SELECT 
	'e'||`id` AS `id`,`date`,`duration`,`seconds_paused`,`calories_burned`,`calories_burned_carbs`,`calories_burned_fats`,
	`HR_lowest`,`HR_peak`,`HR_average`,NULL AS `time_rule`,`HR_data`,`UV`,`UV_exposure_seconds`,`cardio_benefit`, "Exercise" AS `event_type`
	FROM `Exercise`

	ORDER BY `Date`
;
